In [1]:
import numpy as np
zeros = np.zeros(10, dtype=int)
print("The dimension of array zeros is",zeros.ndim)
print("The shape of array zeros is",zeros.shape)
print("The size of array zeros is",zeros.size)
print("Data type of the items in zeros array is ",zeros.dtype)
print("The itemsize of array is",zeros.itemsize)

The dimension of array zeros is 1
The shape of array zeros is (10,)
The size of array zeros is 10
Data type of the items in zeros array is  int32
The itemsize of array is 4


In [2]:
vowels = np.array(["a","e","i","o","u"])
print("The dimension of array vowels is",vowels.ndim)
print("The shape of array vowels is",vowels.shape)
print("The size of array vowels is",vowels.size)
print("Data type of the items in vowels array is ",vowels.dtype)
print("The itemsize of array is",vowels.itemsize)

The dimension of array vowels is 1
The shape of array vowels is (5,)
The size of array vowels is 5
Data type of the items in vowels array is  <U1
The itemsize of array is 4


In [3]:
ones = np.ones((2,5),dtype=int)
print("The dimension of array ones is",ones.ndim)
print("The shape of array vowels is",ones.shape)
print("The size of array vowels is",ones.size)
print("Data type of the items in ones array is ",ones.dtype)
print("The itemsize of array is",ones.itemsize)

The dimension of array ones is 2
The shape of array vowels is (2, 5)
The size of array vowels is 10
Data type of the items in ones array is  int32
The itemsize of array is 4


In [4]:
myarray1 = np.array([[2.7,-2,-19],[0, 3.4, 99.9],[10.6, 0, 13]])
print("The dimension of array myarray1 is",myarray1.ndim)
print("The shape of array myarray1 is",myarray1.shape)
print("The size of array myarray1 is",myarray1.size)
print("Data type of the items in myarray1 array is ",myarray1.dtype)
print("The itemsize of array is",myarray1.itemsize)

The dimension of array myarray1 is 2
The shape of array myarray1 is (3, 3)
The size of array myarray1 is 9
Data type of the items in myarray1 array is  float64
The itemsize of array is 8


In [5]:
myarray2 = np.arange(start=4, stop=64, step=4, dtype=float) 
myarray2 = myarray2.reshape((3,5))
print("The dimension of array myarray2 is",myarray2.ndim)
print("The shape of array myarray2 is",myarray2.shape)
print("The size of array myarray2 is",myarray2.size)
print("Data type of the items in zeros array is ",myarray2.dtype)
print("The itemsize of array is",myarray2.itemsize)

The dimension of array myarray2 is 2
The shape of array myarray2 is (3, 5)
The size of array myarray2 is 15
Data type of the items in zeros array is  float64
The itemsize of array is 8


In [6]:
import numpy as np
ones = np.ones((2,5),dtype=int)
b=np.reshape(ones,(10,))
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [8]:
import numpy as np
vowels = np.array(["a","e","i","o","u"])
print(" vowels array elements ")
print(vowels)
print("2nd and 3rd element of the array vowels")
print(vowels[1:3])  # display the 2nd and 3rd element of array

 vowels array elements 
['a' 'e' 'i' 'o' 'u']
2nd and 3rd element of the array vowels
['e' 'i']


In [9]:
import numpy as np
x= np.array([[2.7,-2,-19], [0,3.4,99.9],[10.6,0, 13]])
print(" myarray1 elements ")
print(x)
print("Display all elements in the 2nd and 3rd row of the array myarray1")
print(x[1])    
print(x[2])   

 myarray1 elements 
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]
Display all elements in the 2nd and 3rd row of the array myarray1
[ 0.   3.4 99.9]
[10.6  0.  13. ]


In [10]:
import numpy as np
x= np.array([[2.7,-2,-19], [0,3.4,99.9],[10.6,0, 13]])
print(" myarray1 elements ")
print(x)
print("Display all elements in the 1st and 2nd column of the array myarray1")
print(x[:,0])
print(x[:,1])

 myarray1 elements 
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]
Display all elements in the 1st and 2nd column of the array myarray1
[ 2.7  0.  10.6]
[-2.   3.4  0. ]


In [12]:
import numpy as np
x= np.array([[2.7,-2,-19], [0,3.4,99.9],[10.6,0, 13]])
print(" myarray1 elements ")
print(x)
print("Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1")
print(x[-2:3,0])

 myarray1 elements 
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]
Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1
[ 0.  10.6]


In [13]:
import numpy as np
vowels = np.array(["a","e","i","o","u"])
print(" vowels array elements ")
print(vowels)
print("Reversed array of vowels")
print(vowels[::-1])

 vowels array elements 
['a' 'e' 'i' 'o' 'u']
Reversed array of vowels
['u' 'o' 'i' 'e' 'a']
